# Generated by Django 5.2 on 2025-05-06 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('age', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)], verbose_name='Возраст')),
                ('sex', models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], max_length=10, verbose_name='Пол')),
                ('active', models.BooleanField(verbose_name='Активный')),
            ],
        ),
    ]
