# Generated by Django 5.2 on 2025-05-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='student',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время изменения'),
        ),
    ]
