# Generated by Django 5.0.3 on 2025-05-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(blank=True, help_text='только латинские', max_length=255, verbose_name='URL'),
        ),
    ]
