# Generated by Django 5.0.3 on 2025-05-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_student_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.SlugField(help_text='только латинские', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
